package com.shirtstore.entity;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import java.util.Objects;

import javax.persistence.*;

/**
 * OrderDetailId generated by hbm2java
 */
//to hợp khóa chính
@Embeddable
public class OrderDetailId implements java.io.Serializable {
	private Shirt shirt;
	private ShirtOrder shirtOrder;
	private String size;
	
	public OrderDetailId() {
	}

	public OrderDetailId(Shirt shirt, ShirtOrder shirtOrder, String size) {
		this.shirt = shirt;
		this.shirtOrder = shirtOrder;
		this.size = size;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Shirt getShirt() {
		return this.shirt;
	}

	public void setShirt(Shirt shirt) {
		this.shirt = shirt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public ShirtOrder getShirtOrder() {
		return this.shirtOrder;
	}

	public void setShirtOrder(ShirtOrder shirtOrder) {
		this.shirtOrder = shirtOrder;
	}

	@Column(name ="size", nullable = false)
	public String getSize() {
		return size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Override
	public int hashCode() {
		return Objects.hash(shirt, shirtOrder);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetailId other = (OrderDetailId) obj;
		return Objects.equals(shirt, other.shirt) && Objects.equals(shirtOrder, other.shirtOrder);
	}
}
