package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * HostSummaryByFileIoType generated by hbm2java
 */
public class HostSummaryByFileIoType implements java.io.Serializable {

	private HostSummaryByFileIoTypeId id;

	public HostSummaryByFileIoType() {
	}

	public HostSummaryByFileIoType(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public HostSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
