package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * HostSummaryByStatementType generated by hbm2java
 */
public class HostSummaryByStatementType implements java.io.Serializable {

	private HostSummaryByStatementTypeId id;

	public HostSummaryByStatementType() {
	}

	public HostSummaryByStatementType(HostSummaryByStatementTypeId id) {
		this.id = id;
	}

	public HostSummaryByStatementTypeId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStatementTypeId id) {
		this.id = id;
	}

}
