package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * InnodbBufferStatsBySchema generated by hbm2java
 */
public class InnodbBufferStatsBySchema implements java.io.Serializable {

	private InnodbBufferStatsBySchemaId id;

	public InnodbBufferStatsBySchema() {
	}

	public InnodbBufferStatsBySchema(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

	public InnodbBufferStatsBySchemaId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

}
