package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * IoGlobalByWaitByLatency generated by hbm2java
 */
public class IoGlobalByWaitByLatency implements java.io.Serializable {

	private IoGlobalByWaitByLatencyId id;

	public IoGlobalByWaitByLatency() {
	}

	public IoGlobalByWaitByLatency(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

	public IoGlobalByWaitByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

}
