package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * MemoryByThreadByCurrentBytes generated by hbm2java
 */
public class MemoryByThreadByCurrentBytes implements java.io.Serializable {

	private MemoryByThreadByCurrentBytesId id;

	public MemoryByThreadByCurrentBytes() {
	}

	public MemoryByThreadByCurrentBytes(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByThreadByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

}
