package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * Processlist generated by hbm2java
 */
public class Processlist implements java.io.Serializable {

	private ProcesslistId id;

	public Processlist() {
	}

	public Processlist(ProcesslistId id) {
		this.id = id;
	}

	public ProcesslistId getId() {
		return this.id;
	}

	public void setId(ProcesslistId id) {
		this.id = id;
	}

}
