package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Rate generated by hbm2java
 */
public class Rate implements java.io.Serializable {

	private Integer rateId;
	private Customer customer;
	private Shoe shoe;
	private int ratingStars;
	private String headline;
	private String ratingDetail;
	private Date rateTime;

	public Rate() {
	}

	public Rate(Customer customer, Shoe shoe, int ratingStars, String headline, String ratingDetail, Date rateTime) {
		this.customer = customer;
		this.shoe = shoe;
		this.ratingStars = ratingStars;
		this.headline = headline;
		this.ratingDetail = ratingDetail;
		this.rateTime = rateTime;
	}

	public Integer getRateId() {
		return this.rateId;
	}

	public void setRateId(Integer rateId) {
		this.rateId = rateId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Shoe getShoe() {
		return this.shoe;
	}

	public void setShoe(Shoe shoe) {
		this.shoe = shoe;
	}

	public int getRatingStars() {
		return this.ratingStars;
	}

	public void setRatingStars(int ratingStars) {
		this.ratingStars = ratingStars;
	}

	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	public String getRatingDetail() {
		return this.ratingDetail;
	}

	public void setRatingDetail(String ratingDetail) {
		this.ratingDetail = ratingDetail;
	}

	public Date getRateTime() {
		return this.rateTime;
	}

	public void setRateTime(Date rateTime) {
		this.rateTime = rateTime;
	}

}
