package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * SchemaAutoIncrementColumns generated by hbm2java
 */
public class SchemaAutoIncrementColumns implements java.io.Serializable {

	private SchemaAutoIncrementColumnsId id;

	public SchemaAutoIncrementColumns() {
	}

	public SchemaAutoIncrementColumns(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

	public SchemaAutoIncrementColumnsId getId() {
		return this.id;
	}

	public void setId(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

}
