package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * SchemaTableStatisticsWithBuffer generated by hbm2java
 */
public class SchemaTableStatisticsWithBuffer implements java.io.Serializable {

	private SchemaTableStatisticsWithBufferId id;

	public SchemaTableStatisticsWithBuffer() {
	}

	public SchemaTableStatisticsWithBuffer(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

	public SchemaTableStatisticsWithBufferId getId() {
		return this.id;
	}

	public void setId(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

}
