package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * SchemaUnusedIndexes generated by hbm2java
 */
public class SchemaUnusedIndexes implements java.io.Serializable {

	private SchemaUnusedIndexesId id;

	public SchemaUnusedIndexes() {
	}

	public SchemaUnusedIndexes(SchemaUnusedIndexesId id) {
		this.id = id;
	}

	public SchemaUnusedIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaUnusedIndexesId id) {
		this.id = id;
	}

}
