package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * SchemaTablesWithFullTableScans generated by hbm2java
 */
public class SchemaTablesWithFullTableScans implements java.io.Serializable {

	private SchemaTablesWithFullTableScansId id;

	public SchemaTablesWithFullTableScans() {
	}

	public SchemaTablesWithFullTableScans(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

	public SchemaTablesWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

}
