package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * SchemaObjectOverview generated by hbm2java
 */
public class SchemaObjectOverview implements java.io.Serializable {

	private SchemaObjectOverviewId id;

	public SchemaObjectOverview() {
	}

	public SchemaObjectOverview(SchemaObjectOverviewId id) {
		this.id = id;
	}

	public SchemaObjectOverviewId getId() {
		return this.id;
	}

	public void setId(SchemaObjectOverviewId id) {
		this.id = id;
	}

}
