package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * SchemaTableLockWaits generated by hbm2java
 */
public class SchemaTableLockWaits implements java.io.Serializable {

	private SchemaTableLockWaitsId id;

	public SchemaTableLockWaits() {
	}

	public SchemaTableLockWaits(SchemaTableLockWaitsId id) {
		this.id = id;
	}

	public SchemaTableLockWaitsId getId() {
		return this.id;
	}

	public void setId(SchemaTableLockWaitsId id) {
		this.id = id;
	}

}
