package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShoeOrder generated by hbm2java
 */
public class ShoeOrder implements java.io.Serializable {

	private Integer orderId;
	private Customer customer;
	private Date orderDate;
	private String toAddress;
	private String recipientName;
	private String recipientPhone;
	private String payment;
	private float orderSum;
	private String status;
	private Set orderDetails = new HashSet(0);

	public ShoeOrder() {
	}

	public ShoeOrder(Customer customer, Date orderDate, String toAddress, String recipientName, String recipientPhone,
			String payment, float orderSum, String status) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.toAddress = toAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.payment = payment;
		this.orderSum = orderSum;
		this.status = status;
	}

	public ShoeOrder(Customer customer, Date orderDate, String toAddress, String recipientName, String recipientPhone,
			String payment, float orderSum, String status, Set orderDetails) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.toAddress = toAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.payment = payment;
		this.orderSum = orderSum;
		this.status = status;
		this.orderDetails = orderDetails;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	public String getRecipientName() {
		return this.recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	public String getRecipientPhone() {
		return this.recipientPhone;
	}

	public void setRecipientPhone(String recipientPhone) {
		this.recipientPhone = recipientPhone;
	}

	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	public float getOrderSum() {
		return this.orderSum;
	}

	public void setOrderSum(float orderSum) {
		this.orderSum = orderSum;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
