package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * StatementsWithFullTableScans generated by hbm2java
 */
public class StatementsWithFullTableScans implements java.io.Serializable {

	private StatementsWithFullTableScansId id;

	public StatementsWithFullTableScans() {
	}

	public StatementsWithFullTableScans(StatementsWithFullTableScansId id) {
		this.id = id;
	}

	public StatementsWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(StatementsWithFullTableScansId id) {
		this.id = id;
	}

}
