package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * StatementsWithTempTables generated by hbm2java
 */
public class StatementsWithTempTables implements java.io.Serializable {

	private StatementsWithTempTablesId id;

	public StatementsWithTempTables() {
	}

	public StatementsWithTempTables(StatementsWithTempTablesId id) {
		this.id = id;
	}

	public StatementsWithTempTablesId getId() {
		return this.id;
	}

	public void setId(StatementsWithTempTablesId id) {
		this.id = id;
	}

}
