package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * StatementsWithSorting generated by hbm2java
 */
public class StatementsWithSorting implements java.io.Serializable {

	private StatementsWithSortingId id;

	public StatementsWithSorting() {
	}

	public StatementsWithSorting(StatementsWithSortingId id) {
		this.id = id;
	}

	public StatementsWithSortingId getId() {
		return this.id;
	}

	public void setId(StatementsWithSortingId id) {
		this.id = id;
	}

}
