package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final

/**
 * WaitsByUserByLatency generated by hbm2java
 */
public class WaitsByUserByLatency implements java.io.Serializable {

	private WaitsByUserByLatencyId id;

	public WaitsByUserByLatency() {
	}

	public WaitsByUserByLatency(WaitsByUserByLatencyId id) {
		this.id = id;
	}

	public WaitsByUserByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsByUserByLatencyId id) {
		this.id = id;
	}

}
