package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.hostSummaryByFileIoTypeId;

/**
 * X.hostSummaryByFileIoType generated by hbm2java
 */
public class X.hostSummaryByFileIoType  implements java.io.Serializable {


     private X.hostSummaryByFileIoTypeId id;

    public X.hostSummaryByFileIoType() {
    }

    public X.hostSummaryByFileIoType(X.hostSummaryByFileIoTypeId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoTypeId id) {
        this.id = id;
    }




}


