package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.innodbLockWaitsId;

/**
 * X.innodbLockWaits generated by hbm2java
 */
public class X.innodbLockWaits  implements java.io.Serializable {


     private X.innodbLockWaitsId id;

    public X.innodbLockWaits() {
    }

    public X.innodbLockWaits(X.innodbLockWaitsId id) {
       this.id = id;
    }
   
    public X.innodbLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.innodbLockWaitsId id) {
        this.id = id;
    }




}


