package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.innodbBufferStatsByTableId;

/**
 * X.innodbBufferStatsByTable generated by hbm2java
 */
public class X.innodbBufferStatsByTable  implements java.io.Serializable {


     private X.innodbBufferStatsByTableId id;

    public X.innodbBufferStatsByTable() {
    }

    public X.innodbBufferStatsByTable(X.innodbBufferStatsByTableId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsByTableId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsByTableId id) {
        this.id = id;
    }




}


