package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.ioGlobalByWaitByLatencyId;

/**
 * X.ioGlobalByWaitByLatency generated by hbm2java
 */
public class X.ioGlobalByWaitByLatency  implements java.io.Serializable {


     private X.ioGlobalByWaitByLatencyId id;

    public X.ioGlobalByWaitByLatency() {
    }

    public X.ioGlobalByWaitByLatency(X.ioGlobalByWaitByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByLatencyId id) {
        this.id = id;
    }




}


