package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.memoryGlobalByCurrentBytesId;

/**
 * X.memoryGlobalByCurrentBytes generated by hbm2java
 */
public class X.memoryGlobalByCurrentBytes  implements java.io.Serializable {


     private X.memoryGlobalByCurrentBytesId id;

    public X.memoryGlobalByCurrentBytes() {
    }

    public X.memoryGlobalByCurrentBytes(X.memoryGlobalByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryGlobalByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryGlobalByCurrentBytesId id) {
        this.id = id;
    }




}


