package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.memoryByUserByCurrentBytesId;

/**
 * X.memoryByUserByCurrentBytes generated by hbm2java
 */
public class X.memoryByUserByCurrentBytes  implements java.io.Serializable {


     private X.memoryByUserByCurrentBytesId id;

    public X.memoryByUserByCurrentBytes() {
    }

    public X.memoryByUserByCurrentBytes(X.memoryByUserByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByUserByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByUserByCurrentBytesId id) {
        this.id = id;
    }




}


