package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.psDigestAvgLatencyDistributionId;

/**
 * X.psDigestAvgLatencyDistribution generated by hbm2java
 */
public class X.psDigestAvgLatencyDistribution  implements java.io.Serializable {


     private X.psDigestAvgLatencyDistributionId id;

    public X.psDigestAvgLatencyDistribution() {
    }

    public X.psDigestAvgLatencyDistribution(X.psDigestAvgLatencyDistributionId id) {
       this.id = id;
    }
   
    public X.psDigestAvgLatencyDistributionId getId() {
        return this.id;
    }
    
    public void setId(X.psDigestAvgLatencyDistributionId id) {
        this.id = id;
    }




}


