package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.schemaTableLockWaitsId;

/**
 * X.schemaTableLockWaits generated by hbm2java
 */
public class X.schemaTableLockWaits  implements java.io.Serializable {


     private X.schemaTableLockWaitsId id;

    public X.schemaTableLockWaits() {
    }

    public X.schemaTableLockWaits(X.schemaTableLockWaitsId id) {
       this.id = id;
    }
   
    public X.schemaTableLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableLockWaitsId id) {
        this.id = id;
    }




}


