package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.statementsWithFullTableScansId;

/**
 * X.statementsWithFullTableScans generated by hbm2java
 */
public class X.statementsWithFullTableScans  implements java.io.Serializable {


     private X.statementsWithFullTableScansId id;

    public X.statementsWithFullTableScans() {
    }

    public X.statementsWithFullTableScans(X.statementsWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.statementsWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithFullTableScansId id) {
        this.id = id;
    }




}


