package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.statementsWithSortingId;

/**
 * X.statementsWithSorting generated by hbm2java
 */
public class X.statementsWithSorting  implements java.io.Serializable {


     private X.statementsWithSortingId id;

    public X.statementsWithSorting() {
    }

    public X.statementsWithSorting(X.statementsWithSortingId id) {
       this.id = id;
    }
   
    public X.statementsWithSortingId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithSortingId id) {
        this.id = id;
    }




}


