package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.statementsWithRuntimesIn95thPercentileId;

/**
 * X.statementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class X.statementsWithRuntimesIn95thPercentile  implements java.io.Serializable {


     private X.statementsWithRuntimesIn95thPercentileId id;

    public X.statementsWithRuntimesIn95thPercentile() {
    }

    public X.statementsWithRuntimesIn95thPercentile(X.statementsWithRuntimesIn95thPercentileId id) {
       this.id = id;
    }
   
    public X.statementsWithRuntimesIn95thPercentileId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithRuntimesIn95thPercentileId id) {
        this.id = id;
    }




}


