package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.statementsWithErrorsOrWarningsId;

/**
 * X.statementsWithErrorsOrWarnings generated by hbm2java
 */
public class X.statementsWithErrorsOrWarnings  implements java.io.Serializable {


     private X.statementsWithErrorsOrWarningsId id;

    public X.statementsWithErrorsOrWarnings() {
    }

    public X.statementsWithErrorsOrWarnings(X.statementsWithErrorsOrWarningsId id) {
       this.id = id;
    }
   
    public X.statementsWithErrorsOrWarningsId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithErrorsOrWarningsId id) {
        this.id = id;
    }




}


