package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.userSummaryByStatementTypeId;

/**
 * X.userSummaryByStatementType generated by hbm2java
 */
public class X.userSummaryByStatementType  implements java.io.Serializable {


     private X.userSummaryByStatementTypeId id;

    public X.userSummaryByStatementType() {
    }

    public X.userSummaryByStatementType(X.userSummaryByStatementTypeId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementTypeId id) {
        this.id = id;
    }




}


