package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.userSummaryByStatementLatencyId;

/**
 * X.userSummaryByStatementLatency generated by hbm2java
 */
public class X.userSummaryByStatementLatency  implements java.io.Serializable {


     private X.userSummaryByStatementLatencyId id;

    public X.userSummaryByStatementLatency() {
    }

    public X.userSummaryByStatementLatency(X.userSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


