package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.userSummaryByFileIoId;

/**
 * X.userSummaryByFileIo generated by hbm2java
 */
public class X.userSummaryByFileIo  implements java.io.Serializable {


     private X.userSummaryByFileIoId id;

    public X.userSummaryByFileIo() {
    }

    public X.userSummaryByFileIo(X.userSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoId id) {
        this.id = id;
    }




}


