package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.waitsByHostByLatencyId;

/**
 * X.waitsByHostByLatency generated by hbm2java
 */
public class X.waitsByHostByLatency  implements java.io.Serializable {


     private X.waitsByHostByLatencyId id;

    public X.waitsByHostByLatency() {
    }

    public X.waitsByHostByLatency(X.waitsByHostByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByHostByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByHostByLatencyId id) {
        this.id = id;
    }




}


