package com.shoestoredb.entity2;
// Generated Apr 19, 2024, 5:25:59 PM by Hibernate Tools 5.6.15.Final


import com.shoestoredb.entity2.X.waitClassesGlobalByAvgLatencyId;

/**
 * X.waitClassesGlobalByAvgLatency generated by hbm2java
 */
public class X.waitClassesGlobalByAvgLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByAvgLatencyId id;

    public X.waitClassesGlobalByAvgLatency() {
    }

    public X.waitClassesGlobalByAvgLatency(X.waitClassesGlobalByAvgLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByAvgLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByAvgLatencyId id) {
        this.id = id;
    }




}


