package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IoByThreadByLatency generated by hbm2java
 */
@Entity
@Table(name = "io_by_thread_by_latency", catalog = "sys")
public class IoByThreadByLatency implements java.io.Serializable {

	private IoByThreadByLatencyId id;

	public IoByThreadByLatency() {
	}

	public IoByThreadByLatency(IoByThreadByLatencyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "user", column = @Column(name = "user", length = 288)),
			@AttributeOverride(name = "total", column = @Column(name = "total", precision = 42, scale = 0)),
			@AttributeOverride(name = "totalLatency", column = @Column(name = "total_latency", length = 11)),
			@AttributeOverride(name = "minLatency", column = @Column(name = "min_latency", length = 11)),
			@AttributeOverride(name = "avgLatency", column = @Column(name = "avg_latency", length = 11)),
			@AttributeOverride(name = "maxLatency", column = @Column(name = "max_latency", length = 11)),
			@AttributeOverride(name = "threadId", column = @Column(name = "thread_id", nullable = false)),
			@AttributeOverride(name = "processlistId", column = @Column(name = "processlist_id")) })
	public IoByThreadByLatencyId getId() {
		return this.id;
	}

	public void setId(IoByThreadByLatencyId id) {
		this.id = id;
	}

}
