package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IoGlobalByFileByBytes generated by hbm2java
 */
@Entity
@Table(name = "io_global_by_file_by_bytes", catalog = "sys")
public class IoGlobalByFileByBytes implements java.io.Serializable {

	private IoGlobalByFileByBytesId id;

	public IoGlobalByFileByBytes() {
	}

	public IoGlobalByFileByBytes(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "file", column = @Column(name = "file", length = 512)),
			@AttributeOverride(name = "countRead", column = @Column(name = "count_read", nullable = false)),
			@AttributeOverride(name = "totalRead", column = @Column(name = "total_read", length = 11)),
			@AttributeOverride(name = "avgRead", column = @Column(name = "avg_read", length = 11)),
			@AttributeOverride(name = "countWrite", column = @Column(name = "count_write", nullable = false)),
			@AttributeOverride(name = "totalWritten", column = @Column(name = "total_written", length = 11)),
			@AttributeOverride(name = "avgWrite", column = @Column(name = "avg_write", length = 11)),
			@AttributeOverride(name = "total", column = @Column(name = "total", length = 11)),
			@AttributeOverride(name = "writePct", column = @Column(name = "write_pct", nullable = false, precision = 26)) })
	public IoGlobalByFileByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

}
