package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IoGlobalByFileByLatency generated by hbm2java
 */
@Entity
@Table(name = "io_global_by_file_by_latency", catalog = "sys")
public class IoGlobalByFileByLatency implements java.io.Serializable {

	private IoGlobalByFileByLatencyId id;

	public IoGlobalByFileByLatency() {
	}

	public IoGlobalByFileByLatency(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "file", column = @Column(name = "file", length = 512)),
			@AttributeOverride(name = "total", column = @Column(name = "total", nullable = false)),
			@AttributeOverride(name = "totalLatency", column = @Column(name = "total_latency", length = 11)),
			@AttributeOverride(name = "countRead", column = @Column(name = "count_read", nullable = false)),
			@AttributeOverride(name = "readLatency", column = @Column(name = "read_latency", length = 11)),
			@AttributeOverride(name = "countWrite", column = @Column(name = "count_write", nullable = false)),
			@AttributeOverride(name = "writeLatency", column = @Column(name = "write_latency", length = 11)),
			@AttributeOverride(name = "countMisc", column = @Column(name = "count_misc", nullable = false)),
			@AttributeOverride(name = "miscLatency", column = @Column(name = "misc_latency", length = 11)) })
	public IoGlobalByFileByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

}
