package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MemoryByThreadByCurrentBytes generated by hbm2java
 */
@Entity
@Table(name = "memory_by_thread_by_current_bytes", catalog = "sys")
public class MemoryByThreadByCurrentBytes implements java.io.Serializable {

	private MemoryByThreadByCurrentBytesId id;

	public MemoryByThreadByCurrentBytes() {
	}

	public MemoryByThreadByCurrentBytes(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "threadId", column = @Column(name = "thread_id", nullable = false)),
			@AttributeOverride(name = "user", column = @Column(name = "user", length = 288)),
			@AttributeOverride(name = "currentCountUsed", column = @Column(name = "current_count_used", precision = 41, scale = 0)),
			@AttributeOverride(name = "currentAllocated", column = @Column(name = "current_allocated", length = 11)),
			@AttributeOverride(name = "currentAvgAlloc", column = @Column(name = "current_avg_alloc", length = 11)),
			@AttributeOverride(name = "currentMaxAlloc", column = @Column(name = "current_max_alloc", length = 11)),
			@AttributeOverride(name = "totalAllocated", column = @Column(name = "total_allocated", length = 11)) })
	public MemoryByThreadByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

}
