package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MemoryGlobalByCurrentBytes generated by hbm2java
 */
@Entity
@Table(name = "memory_global_by_current_bytes", catalog = "sys")
public class MemoryGlobalByCurrentBytes implements java.io.Serializable {

	private MemoryGlobalByCurrentBytesId id;

	public MemoryGlobalByCurrentBytes() {
	}

	public MemoryGlobalByCurrentBytes(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "eventName", column = @Column(name = "event_name", nullable = false, length = 128)),
			@AttributeOverride(name = "currentCount", column = @Column(name = "current_count", nullable = false)),
			@AttributeOverride(name = "currentAlloc", column = @Column(name = "current_alloc", length = 11)),
			@AttributeOverride(name = "currentAvgAlloc", column = @Column(name = "current_avg_alloc", length = 11)),
			@AttributeOverride(name = "highCount", column = @Column(name = "high_count", nullable = false)),
			@AttributeOverride(name = "highAlloc", column = @Column(name = "high_alloc", length = 11)),
			@AttributeOverride(name = "highAvgAlloc", column = @Column(name = "high_avg_alloc", length = 11)) })
	public MemoryGlobalByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

}
