package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SchemaRedundantIndexes generated by hbm2java
 */
@Entity
@Table(name = "schema_redundant_indexes", catalog = "sys")
public class SchemaRedundantIndexes implements java.io.Serializable {

	private SchemaRedundantIndexesId id;

	public SchemaRedundantIndexes() {
	}

	public SchemaRedundantIndexes(SchemaRedundantIndexesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tableSchema", column = @Column(name = "table_schema", length = 64)),
			@AttributeOverride(name = "tableName", column = @Column(name = "table_name", length = 64)),
			@AttributeOverride(name = "redundantIndexName", column = @Column(name = "redundant_index_name", length = 64)),
			@AttributeOverride(name = "redundantIndexColumns", column = @Column(name = "redundant_index_columns", length = 65535)),
			@AttributeOverride(name = "redundantIndexNonUnique", column = @Column(name = "redundant_index_non_unique")),
			@AttributeOverride(name = "dominantIndexName", column = @Column(name = "dominant_index_name", length = 64)),
			@AttributeOverride(name = "dominantIndexColumns", column = @Column(name = "dominant_index_columns", length = 65535)),
			@AttributeOverride(name = "dominantIndexNonUnique", column = @Column(name = "dominant_index_non_unique")),
			@AttributeOverride(name = "subpartExists", column = @Column(name = "subpart_exists", nullable = false)),
			@AttributeOverride(name = "sqlDropIndex", column = @Column(name = "sql_drop_index", length = 223)) })
	public SchemaRedundantIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaRedundantIndexesId id) {
		this.id = id;
	}

}
