package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SchemaTablesWithFullTableScans generated by hbm2java
 */
@Entity
@Table(name = "schema_tables_with_full_table_scans", catalog = "sys")
public class SchemaTablesWithFullTableScans implements java.io.Serializable {

	private SchemaTablesWithFullTableScansId id;

	public SchemaTablesWithFullTableScans() {
	}

	public SchemaTablesWithFullTableScans(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "objectSchema", column = @Column(name = "object_schema", length = 64)),
			@AttributeOverride(name = "objectName", column = @Column(name = "object_name", length = 64)),
			@AttributeOverride(name = "rowsFullScanned", column = @Column(name = "rows_full_scanned", nullable = false)),
			@AttributeOverride(name = "latency", column = @Column(name = "latency", length = 11)) })
	public SchemaTablesWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

}
