package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SchemaAutoIncrementColumns generated by hbm2java
 */
@Entity
@Table(name = "schema_auto_increment_columns", catalog = "sys")
public class SchemaAutoIncrementColumns implements java.io.Serializable {

	private SchemaAutoIncrementColumnsId id;

	public SchemaAutoIncrementColumns() {
	}

	public SchemaAutoIncrementColumns(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tableSchema", column = @Column(name = "table_schema", length = 64)),
			@AttributeOverride(name = "tableName", column = @Column(name = "table_name", length = 64)),
			@AttributeOverride(name = "columnName", column = @Column(name = "column_name", length = 64)),
			@AttributeOverride(name = "dataType", column = @Column(name = "data_type")),
			@AttributeOverride(name = "columnType", column = @Column(name = "column_type", nullable = false, length = 16777215)),
			@AttributeOverride(name = "isSigned", column = @Column(name = "is_signed", nullable = false)),
			@AttributeOverride(name = "isUnsigned", column = @Column(name = "is_unsigned", nullable = false)),
			@AttributeOverride(name = "maxValue", column = @Column(name = "max_value")),
			@AttributeOverride(name = "autoIncrement", column = @Column(name = "auto_increment")),
			@AttributeOverride(name = "autoIncrementRatio", column = @Column(name = "auto_increment_ratio", precision = 25, scale = 4)) })
	public SchemaAutoIncrementColumnsId getId() {
		return this.id;
	}

	public void setId(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

}
