package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SchemaUnusedIndexes generated by hbm2java
 */
@Entity
@Table(name = "schema_unused_indexes", catalog = "sys")
public class SchemaUnusedIndexes implements java.io.Serializable {

	private SchemaUnusedIndexesId id;

	public SchemaUnusedIndexes() {
	}

	public SchemaUnusedIndexes(SchemaUnusedIndexesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "objectSchema", column = @Column(name = "object_schema", length = 64)),
			@AttributeOverride(name = "objectName", column = @Column(name = "object_name", length = 64)),
			@AttributeOverride(name = "indexName", column = @Column(name = "index_name", length = 64)) })
	public SchemaUnusedIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaUnusedIndexesId id) {
		this.id = id;
	}

}
