package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SessionSslStatus generated by hbm2java
 */
@Entity
@Table(name = "session_ssl_status", catalog = "sys")
public class SessionSslStatus implements java.io.Serializable {

	private SessionSslStatusId id;

	public SessionSslStatus() {
	}

	public SessionSslStatus(SessionSslStatusId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "threadId", column = @Column(name = "thread_id", nullable = false)),
			@AttributeOverride(name = "sslVersion", column = @Column(name = "ssl_version", length = 1024)),
			@AttributeOverride(name = "sslCipher", column = @Column(name = "ssl_cipher", length = 1024)),
			@AttributeOverride(name = "sslSessionsReused", column = @Column(name = "ssl_sessions_reused", length = 1024)) })
	public SessionSslStatusId getId() {
		return this.id;
	}

	public void setId(SessionSslStatusId id) {
		this.id = id;
	}

}
