package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WaitsGlobalByLatencyId generated by hbm2java
 */
@Embeddable
public class WaitsGlobalByLatencyId implements java.io.Serializable {

	private String events;
	private long total;
	private String totalLatency;
	private String avgLatency;
	private String maxLatency;

	public WaitsGlobalByLatencyId() {
	}

	public WaitsGlobalByLatencyId(String events, long total) {
		this.events = events;
		this.total = total;
	}

	public WaitsGlobalByLatencyId(String events, long total, String totalLatency, String avgLatency,
			String maxLatency) {
		this.events = events;
		this.total = total;
		this.totalLatency = totalLatency;
		this.avgLatency = avgLatency;
		this.maxLatency = maxLatency;
	}

	@Column(name = "events", nullable = false, length = 128)
	public String getEvents() {
		return this.events;
	}

	public void setEvents(String events) {
		this.events = events;
	}

	@Column(name = "total", nullable = false)
	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	@Column(name = "total_latency", length = 11)
	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	@Column(name = "avg_latency", length = 11)
	public String getAvgLatency() {
		return this.avgLatency;
	}

	public void setAvgLatency(String avgLatency) {
		this.avgLatency = avgLatency;
	}

	@Column(name = "max_latency", length = 11)
	public String getMaxLatency() {
		return this.maxLatency;
	}

	public void setMaxLatency(String maxLatency) {
		this.maxLatency = maxLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WaitsGlobalByLatencyId))
			return false;
		WaitsGlobalByLatencyId castOther = (WaitsGlobalByLatencyId) other;

		return ((this.getEvents() == castOther.getEvents()) || (this.getEvents() != null
				&& castOther.getEvents() != null && this.getEvents().equals(castOther.getEvents())))
				&& (this.getTotal() == castOther.getTotal())
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())))
				&& ((this.getAvgLatency() == castOther.getAvgLatency()) || (this.getAvgLatency() != null
						&& castOther.getAvgLatency() != null && this.getAvgLatency().equals(castOther.getAvgLatency())))
				&& ((this.getMaxLatency() == castOther.getMaxLatency())
						|| (this.getMaxLatency() != null && castOther.getMaxLatency() != null
								&& this.getMaxLatency().equals(castOther.getMaxLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEvents() == null ? 0 : this.getEvents().hashCode());
		result = 37 * result + (int) this.getTotal();
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		result = 37 * result + (getAvgLatency() == null ? 0 : this.getAvgLatency().hashCode());
		result = 37 * result + (getMaxLatency() == null ? 0 : this.getMaxLatency().hashCode());
		return result;
	}

}
