package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WaitClassesGlobalByLatency generated by hbm2java
 */
@Entity
@Table(name = "wait_classes_global_by_latency", catalog = "sys")
public class WaitClassesGlobalByLatency implements java.io.Serializable {

	private WaitClassesGlobalByLatencyId id;

	public WaitClassesGlobalByLatency() {
	}

	public WaitClassesGlobalByLatency(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "eventClass", column = @Column(name = "event_class", length = 128)),
			@AttributeOverride(name = "total", column = @Column(name = "total", precision = 42, scale = 0)),
			@AttributeOverride(name = "totalLatency", column = @Column(name = "total_latency", length = 11)),
			@AttributeOverride(name = "minLatency", column = @Column(name = "min_latency", length = 11)),
			@AttributeOverride(name = "avgLatency", column = @Column(name = "avg_latency", length = 11)),
			@AttributeOverride(name = "maxLatency", column = @Column(name = "max_latency", length = 11)) })
	public WaitClassesGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

}
