package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.hostSummaryByStatementTypeId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.hostSummaryByStatementType generated by hbm2java
 */
@Entity
@Table(name="x$host_summary_by_statement_type"
    ,catalog="sys"
)
public class X.hostSummaryByStatementType  implements java.io.Serializable {


     private X.hostSummaryByStatementTypeId id;

    public X.hostSummaryByStatementType() {
    }

    public X.hostSummaryByStatementType(X.hostSummaryByStatementTypeId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="host", column=@Column(name="host") ), 
        @AttributeOverride(name="statement", column=@Column(name="statement", length=128) ), 
        @AttributeOverride(name="total", column=@Column(name="total", nullable=false) ), 
        @AttributeOverride(name="totalLatency", column=@Column(name="total_latency", nullable=false) ), 
        @AttributeOverride(name="maxLatency", column=@Column(name="max_latency", nullable=false) ), 
        @AttributeOverride(name="lockLatency", column=@Column(name="lock_latency", nullable=false) ), 
        @AttributeOverride(name="cpuLatency", column=@Column(name="cpu_latency", nullable=false) ), 
        @AttributeOverride(name="rowsSent", column=@Column(name="rows_sent", nullable=false) ), 
        @AttributeOverride(name="rowsExamined", column=@Column(name="rows_examined", nullable=false) ), 
        @AttributeOverride(name="rowsAffected", column=@Column(name="rows_affected", nullable=false) ), 
        @AttributeOverride(name="fullScans", column=@Column(name="full_scans", nullable=false) ) } )
    public X.hostSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementTypeId id) {
        this.id = id;
    }




}


