package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.innodbBufferStatsByTableId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.innodbBufferStatsByTable generated by hbm2java
 */
@Entity
@Table(name="x$innodb_buffer_stats_by_table"
    ,catalog="sys"
)
public class X.innodbBufferStatsByTable  implements java.io.Serializable {


     private X.innodbBufferStatsByTableId id;

    public X.innodbBufferStatsByTable() {
    }

    public X.innodbBufferStatsByTable(X.innodbBufferStatsByTableId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="objectSchema", column=@Column(name="object_schema", length=65535) ), 
        @AttributeOverride(name="objectName", column=@Column(name="object_name", length=65535) ), 
        @AttributeOverride(name="allocated", column=@Column(name="allocated", precision=44, scale=0) ), 
        @AttributeOverride(name="data", column=@Column(name="data", precision=44, scale=0) ), 
        @AttributeOverride(name="pages", column=@Column(name="pages", nullable=false) ), 
        @AttributeOverride(name="pagesHashed", column=@Column(name="pages_hashed", nullable=false) ), 
        @AttributeOverride(name="pagesOld", column=@Column(name="pages_old", nullable=false) ), 
        @AttributeOverride(name="rowsCached", column=@Column(name="rows_cached", nullable=false, precision=45, scale=0) ) } )
    public X.innodbBufferStatsByTableId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsByTableId id) {
        this.id = id;
    }




}


