package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.ioGlobalByFileByBytesId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.ioGlobalByFileByBytes generated by hbm2java
 */
@Entity
@Table(name="x$io_global_by_file_by_bytes"
    ,catalog="sys"
)
public class X.ioGlobalByFileByBytes  implements java.io.Serializable {


     private X.ioGlobalByFileByBytesId id;

    public X.ioGlobalByFileByBytes() {
    }

    public X.ioGlobalByFileByBytes(X.ioGlobalByFileByBytesId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="file", column=@Column(name="file", nullable=false, length=512) ), 
        @AttributeOverride(name="countRead", column=@Column(name="count_read", nullable=false) ), 
        @AttributeOverride(name="totalRead", column=@Column(name="total_read", nullable=false) ), 
        @AttributeOverride(name="avgRead", column=@Column(name="avg_read", nullable=false, precision=23, scale=4) ), 
        @AttributeOverride(name="countWrite", column=@Column(name="count_write", nullable=false) ), 
        @AttributeOverride(name="totalWritten", column=@Column(name="total_written", nullable=false) ), 
        @AttributeOverride(name="avgWrite", column=@Column(name="avg_write", nullable=false, precision=23, scale=4) ), 
        @AttributeOverride(name="total", column=@Column(name="total", nullable=false) ), 
        @AttributeOverride(name="writePct", column=@Column(name="write_pct", nullable=false, precision=26) ) } )
    public X.ioGlobalByFileByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByBytesId id) {
        this.id = id;
    }




}


