package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.ioGlobalByWaitByLatencyId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.ioGlobalByWaitByLatency generated by hbm2java
 */
@Entity
@Table(name="x$io_global_by_wait_by_latency"
    ,catalog="sys"
)
public class X.ioGlobalByWaitByLatency  implements java.io.Serializable {


     private X.ioGlobalByWaitByLatencyId id;

    public X.ioGlobalByWaitByLatency() {
    }

    public X.ioGlobalByWaitByLatency(X.ioGlobalByWaitByLatencyId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="eventName", column=@Column(name="event_name", length=128) ), 
        @AttributeOverride(name="total", column=@Column(name="total", nullable=false) ), 
        @AttributeOverride(name="totalLatency", column=@Column(name="total_latency", nullable=false) ), 
        @AttributeOverride(name="avgLatency", column=@Column(name="avg_latency", nullable=false) ), 
        @AttributeOverride(name="maxLatency", column=@Column(name="max_latency", nullable=false) ), 
        @AttributeOverride(name="readLatency", column=@Column(name="read_latency", nullable=false) ), 
        @AttributeOverride(name="writeLatency", column=@Column(name="write_latency", nullable=false) ), 
        @AttributeOverride(name="miscLatency", column=@Column(name="misc_latency", nullable=false) ), 
        @AttributeOverride(name="countRead", column=@Column(name="count_read", nullable=false) ), 
        @AttributeOverride(name="totalRead", column=@Column(name="total_read", nullable=false) ), 
        @AttributeOverride(name="avgRead", column=@Column(name="avg_read", nullable=false, precision=23, scale=4) ), 
        @AttributeOverride(name="countWrite", column=@Column(name="count_write", nullable=false) ), 
        @AttributeOverride(name="totalWritten", column=@Column(name="total_written", nullable=false) ), 
        @AttributeOverride(name="avgWritten", column=@Column(name="avg_written", nullable=false, precision=23, scale=4) ) } )
    public X.ioGlobalByWaitByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByLatencyId id) {
        this.id = id;
    }




}


