package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.psSchemaTableStatisticsIoId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.psSchemaTableStatisticsIo generated by hbm2java
 */
@Entity
@Table(name="x$ps_schema_table_statistics_io"
    ,catalog="sys"
)
public class X.psSchemaTableStatisticsIo  implements java.io.Serializable {


     private X.psSchemaTableStatisticsIoId id;

    public X.psSchemaTableStatisticsIo() {
    }

    public X.psSchemaTableStatisticsIo(X.psSchemaTableStatisticsIoId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tableSchema", column=@Column(name="table_schema", length=64) ), 
        @AttributeOverride(name="tableName", column=@Column(name="table_name", length=64) ), 
        @AttributeOverride(name="countRead", column=@Column(name="count_read", precision=42, scale=0) ), 
        @AttributeOverride(name="sumNumberOfBytesRead", column=@Column(name="sum_number_of_bytes_read", precision=41, scale=0) ), 
        @AttributeOverride(name="sumTimerRead", column=@Column(name="sum_timer_read", precision=42, scale=0) ), 
        @AttributeOverride(name="countWrite", column=@Column(name="count_write", precision=42, scale=0) ), 
        @AttributeOverride(name="sumNumberOfBytesWrite", column=@Column(name="sum_number_of_bytes_write", precision=41, scale=0) ), 
        @AttributeOverride(name="sumTimerWrite", column=@Column(name="sum_timer_write", precision=42, scale=0) ), 
        @AttributeOverride(name="countMisc", column=@Column(name="count_misc", precision=42, scale=0) ), 
        @AttributeOverride(name="sumTimerMisc", column=@Column(name="sum_timer_misc", precision=42, scale=0) ) } )
    public X.psSchemaTableStatisticsIoId getId() {
        return this.id;
    }
    
    public void setId(X.psSchemaTableStatisticsIoId id) {
        this.id = id;
    }




}


