package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.schemaTableStatisticsWithBufferId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.schemaTableStatisticsWithBuffer generated by hbm2java
 */
@Entity
@Table(name="x$schema_table_statistics_with_buffer"
    ,catalog="sys"
)
public class X.schemaTableStatisticsWithBuffer  implements java.io.Serializable {


     private X.schemaTableStatisticsWithBufferId id;

    public X.schemaTableStatisticsWithBuffer() {
    }

    public X.schemaTableStatisticsWithBuffer(X.schemaTableStatisticsWithBufferId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tableSchema", column=@Column(name="table_schema", length=64) ), 
        @AttributeOverride(name="tableName", column=@Column(name="table_name", length=64) ), 
        @AttributeOverride(name="rowsFetched", column=@Column(name="rows_fetched", nullable=false) ), 
        @AttributeOverride(name="fetchLatency", column=@Column(name="fetch_latency", nullable=false) ), 
        @AttributeOverride(name="rowsInserted", column=@Column(name="rows_inserted", nullable=false) ), 
        @AttributeOverride(name="insertLatency", column=@Column(name="insert_latency", nullable=false) ), 
        @AttributeOverride(name="rowsUpdated", column=@Column(name="rows_updated", nullable=false) ), 
        @AttributeOverride(name="updateLatency", column=@Column(name="update_latency", nullable=false) ), 
        @AttributeOverride(name="rowsDeleted", column=@Column(name="rows_deleted", nullable=false) ), 
        @AttributeOverride(name="deleteLatency", column=@Column(name="delete_latency", nullable=false) ), 
        @AttributeOverride(name="ioReadRequests", column=@Column(name="io_read_requests", precision=42, scale=0) ), 
        @AttributeOverride(name="ioRead", column=@Column(name="io_read", precision=41, scale=0) ), 
        @AttributeOverride(name="ioReadLatency", column=@Column(name="io_read_latency", precision=42, scale=0) ), 
        @AttributeOverride(name="ioWriteRequests", column=@Column(name="io_write_requests", precision=42, scale=0) ), 
        @AttributeOverride(name="ioWrite", column=@Column(name="io_write", precision=41, scale=0) ), 
        @AttributeOverride(name="ioWriteLatency", column=@Column(name="io_write_latency", precision=42, scale=0) ), 
        @AttributeOverride(name="ioMiscRequests", column=@Column(name="io_misc_requests", precision=42, scale=0) ), 
        @AttributeOverride(name="ioMiscLatency", column=@Column(name="io_misc_latency", precision=42, scale=0) ), 
        @AttributeOverride(name="innodbBufferAllocated", column=@Column(name="innodb_buffer_allocated", precision=44, scale=0) ), 
        @AttributeOverride(name="innodbBufferData", column=@Column(name="innodb_buffer_data", precision=44, scale=0) ), 
        @AttributeOverride(name="innodbBufferFree", column=@Column(name="innodb_buffer_free", precision=45, scale=0) ), 
        @AttributeOverride(name="innodbBufferPages", column=@Column(name="innodb_buffer_pages") ), 
        @AttributeOverride(name="innodbBufferPagesHashed", column=@Column(name="innodb_buffer_pages_hashed") ), 
        @AttributeOverride(name="innodbBufferPagesOld", column=@Column(name="innodb_buffer_pages_old") ), 
        @AttributeOverride(name="innodbBufferRowsCached", column=@Column(name="innodb_buffer_rows_cached", precision=45, scale=0) ) } )
    public X.schemaTableStatisticsWithBufferId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsWithBufferId id) {
        this.id = id;
    }




}


