package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.schemaFlattenedKeysId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.schemaFlattenedKeys generated by hbm2java
 */
@Entity
@Table(name="x$schema_flattened_keys"
    ,catalog="sys"
)
public class X.schemaFlattenedKeys  implements java.io.Serializable {


     private X.schemaFlattenedKeysId id;

    public X.schemaFlattenedKeys() {
    }

    public X.schemaFlattenedKeys(X.schemaFlattenedKeysId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tableSchema", column=@Column(name="table_schema", length=64) ), 
        @AttributeOverride(name="tableName", column=@Column(name="table_name", length=64) ), 
        @AttributeOverride(name="indexName", column=@Column(name="index_name", length=64) ), 
        @AttributeOverride(name="nonUnique", column=@Column(name="non_unique") ), 
        @AttributeOverride(name="subpartExists", column=@Column(name="subpart_exists") ), 
        @AttributeOverride(name="indexColumns", column=@Column(name="index_columns", length=65535) ) } )
    public X.schemaFlattenedKeysId getId() {
        return this.id;
    }
    
    public void setId(X.schemaFlattenedKeysId id) {
        this.id = id;
    }




}


