package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.statementsWithErrorsOrWarningsId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.statementsWithErrorsOrWarnings generated by hbm2java
 */
@Entity
@Table(name="x$statements_with_errors_or_warnings"
    ,catalog="sys"
)
public class X.statementsWithErrorsOrWarnings  implements java.io.Serializable {


     private X.statementsWithErrorsOrWarningsId id;

    public X.statementsWithErrorsOrWarnings() {
    }

    public X.statementsWithErrorsOrWarnings(X.statementsWithErrorsOrWarningsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="query", column=@Column(name="query") ), 
        @AttributeOverride(name="db", column=@Column(name="db", length=64) ), 
        @AttributeOverride(name="execCount", column=@Column(name="exec_count", nullable=false) ), 
        @AttributeOverride(name="errors", column=@Column(name="errors", nullable=false) ), 
        @AttributeOverride(name="errorPct", column=@Column(name="error_pct", nullable=false, precision=27, scale=4) ), 
        @AttributeOverride(name="warnings", column=@Column(name="warnings", nullable=false) ), 
        @AttributeOverride(name="warningPct", column=@Column(name="warning_pct", nullable=false, precision=27, scale=4) ), 
        @AttributeOverride(name="firstSeen", column=@Column(name="first_seen", nullable=false, length=26) ), 
        @AttributeOverride(name="lastSeen", column=@Column(name="last_seen", nullable=false, length=26) ), 
        @AttributeOverride(name="digest", column=@Column(name="digest", length=64) ) } )
    public X.statementsWithErrorsOrWarningsId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithErrorsOrWarningsId id) {
        this.id = id;
    }




}


