package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.userSummaryId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.userSummary generated by hbm2java
 */
@Entity
@Table(name="x$user_summary"
    ,catalog="sys"
)
public class X.userSummary  implements java.io.Serializable {


     private X.userSummaryId id;

    public X.userSummary() {
    }

    public X.userSummary(X.userSummaryId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="user", column=@Column(name="user", length=32) ), 
        @AttributeOverride(name="statements", column=@Column(name="statements", precision=64, scale=0) ), 
        @AttributeOverride(name="statementLatency", column=@Column(name="statement_latency", precision=64, scale=0) ), 
        @AttributeOverride(name="statementAvgLatency", column=@Column(name="statement_avg_latency", nullable=false, precision=65, scale=4) ), 
        @AttributeOverride(name="tableScans", column=@Column(name="table_scans", precision=65, scale=0) ), 
        @AttributeOverride(name="fileIos", column=@Column(name="file_ios", precision=64, scale=0) ), 
        @AttributeOverride(name="fileIoLatency", column=@Column(name="file_io_latency", precision=64, scale=0) ), 
        @AttributeOverride(name="currentConnections", column=@Column(name="current_connections", precision=41, scale=0) ), 
        @AttributeOverride(name="totalConnections", column=@Column(name="total_connections", precision=41, scale=0) ), 
        @AttributeOverride(name="uniqueHosts", column=@Column(name="unique_hosts", nullable=false) ), 
        @AttributeOverride(name="currentMemory", column=@Column(name="current_memory", precision=63, scale=0) ), 
        @AttributeOverride(name="totalMemoryAllocated", column=@Column(name="total_memory_allocated", precision=64, scale=0) ) } )
    public X.userSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryId id) {
        this.id = id;
    }




}


