package com.shoestoredb.entity3;
// Generated Apr 20, 2024, 2:20:15 PM by Hibernate Tools 4.3.6.Final


import com.shoestoredb.entity3.X.waitClassesGlobalByLatencyId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * X.waitClassesGlobalByLatency generated by hbm2java
 */
@Entity
@Table(name="x$wait_classes_global_by_latency"
    ,catalog="sys"
)
public class X.waitClassesGlobalByLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByLatencyId id;

    public X.waitClassesGlobalByLatency() {
    }

    public X.waitClassesGlobalByLatency(X.waitClassesGlobalByLatencyId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="eventClass", column=@Column(name="event_class", length=128) ), 
        @AttributeOverride(name="total", column=@Column(name="total", precision=42, scale=0) ), 
        @AttributeOverride(name="totalLatency", column=@Column(name="total_latency", precision=42, scale=0) ), 
        @AttributeOverride(name="minLatency", column=@Column(name="min_latency") ), 
        @AttributeOverride(name="avgLatency", column=@Column(name="avg_latency", nullable=false, precision=46, scale=4) ), 
        @AttributeOverride(name="maxLatency", column=@Column(name="max_latency") ) } )
    public X.waitClassesGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByLatencyId id) {
        this.id = id;
    }




}


